const countries = [
    {value: "Argentina", label: "Argentina",},
    {value: "Australia", label: "Australia",},
    {value: "Bangladesh", label: "Bangladesh",},
    {value: "Brazil", label: "Brazil",},
    {value: "Canada", label: "Canada",},
    {value: "China", label: "China",},
    {value: "France", label: "France",},
    {value: "Germany", label: "Germany",},
    {value: "India", label: "India",},
    {value: "Indonesia", label: "Indonesia",},
    {value: "Italy", label: "Italy",},
    {value: "Japan", label: "Japan",},
    {value: "Mexico", label: "Mexico",},
    {value: "Netherlands", label: "Netherlands",},
    {value: "Nigeria", label: "Nigeria",},
    {value: "Philippines", label: "Philippines",},
    {value: "Poland", label: "Poland",},
    {value: "Russia", label: "Russia",},
    {value: "Saudi_Arabia", label: "Saudi Arabia",},
    {value: "South_Africa", label: "South Africa",},
    {value: "South_Korea", label: "South Korea",},
    {value: "Spain", label: "Spain",},
    {value: "Sweden", label: "Sweden",},
    {value: "Switzerland", label: "Switzerland",},
    {value: "Taiwan", label: "Taiwan",},
    {value: "Thailand", label: "Thailand",},
    {value: "Turkey", label: "Turkey",},
    {value: "United_Arab_Emirates", label: "United Arab Emirates",},
    {value: "United_Kingdom", label: "United Kingdom",},
    {value: "United_States", label: "United States",},
    {value: "Vietnam", label: "Vietnam"}
];

export default countries;
